### ISSUE TITLE
Autogenerated test files are also processed

### ISSUE THREAD

**Issue by ukirill** [nathanjcochran/upgrade#2]
Autogenerated test files and package are processed when the module is upgraded. 

When `packages.Load()` run with configuration flag `Test: true`, auto generated and compiled test packages are also exists in result packages collection. This behavior is documented in _golang.org/x/tools/go/packages_ docs. Such auto generated packages contains files from cache or temporary dirs. Processing of such files/packages leads to error.

However, only VCS-controlled source files from module directory are expected to be processed during version upgrade.

Simple case for error is module with _main_test_ packages

main.go

```go
package main

import (
	"fmt"
)

type A struct {
	Prop string
}

func main() {
	fmt.Println(A{})
}
```

main_test.go

```go
package main_test

import (
	"testing"

	main "upmod.my/v2"
)

func TestCreateA(t *testing.T) {
	_ = main.A{"test_string"}
	t.Skip("not imlemented")
}
```

go.mod

```
module upmod.my/v2

go 1.18
```

Trying to execute `upgrade` on such module leads to error:

```
Error rewriting imports: error getting module path for import upmod.my/v2_test: error getting package info: cannot find module providing package upmod.my/v2_test: import lookup disabled by -mod=readonly
```

I could make PR to fix it by processing files from module root dir only if such fix seems correct to you.

**Comment by cochran-at-niche** [comment]
Thanks for submitting this bug report! I don't think setting `Test: false` when loading packages is the solution, because we _do_ need to load the test package so that we can update it's import statements. For example, in this case, if we didn't set `Test: true`, we would never find/load the `main_test.go` file, which means we wouldn't be able to rewrite it's `main "upmod.my/v2"` import to `main "upmod.my/v3"`.

I am looking into alternative solutions. I'll get back to you.

**Comment by nathanjcochran** [comment]
Thanks for submitting this bug report! I don't think setting `Test: false` when loading packages is the solution, because we do need to load the test package so that we can update the import statements in its files. For example, in this case, if we didn't set `Test: true`, we would never find/load the `main_test.go` file (since it's part of the `main_test` package), which means we wouldn't be able to rewrite its `main "upmod.my/v2"` import to `main "upmod.my/v3"`.

I am looking into alternative solutions. I'll get back to you.

**Comment by cochran-at-niche** [comment]
@ukirill This should be fixed by this commit: https://github.com/nathanjcochran/upgrade/commit/ee09661d93daad0ff28efcb0d26bbdd5a2dcb9dd. The solution I settled on involves ignoring all files not rooted within the module directory (such as the "test binary" files, which are typically located within `$HOME/.cache/go-build/`) when rewriting import statements. See [here](https://github.com/nathanjcochran/upgrade/blob/ee09661d93daad0ff28efcb0d26bbdd5a2dcb9dd/imports.go#L59-L69). This fixed the issue when I tested it against your minimal example.

Let me know if you still encounter any issues! And thanks again for submitting the bug report! I really appreciate it :100:
